### ISSUE TITLE
standardize_ts

### ISSUE THREAD

**Issue by morphogenetics** [williamgilpin/fnn#1]
Hi,

Thank you for this amazing resource! In the exploratory.ipynb there doesnt seem to be a function called standardize_ts. Am I missing something? If not would it be possible to include the code for this function in the repo?

**Comment by williamgilpin** [comment]
Thank you! I messed up when I consolidated my files and left that function out. I'm testing now to see if any other functions are missing, and will update accordingly, but for now the function is:

`
def standardize_ts(a, scale=1.0):
    """
    Standardize a T x D time series along its first dimension
    For dimensions with zero variance, divide by zero instead of one
    """
    stds = np.std(a, axis=0, keepdims=True)
    stds[stds==0] = 1
    return (a - np.mean(a, axis=0, keepdims=True))/(scale*stds)
`

**Comment by williamgilpin** [comment]
@morphogenetics I have updated the repo, I also added some plotting functions. thank you again, and please let me know if you run into any other issues

**Comment by morphogenetics** [comment]
Thanks for the prompt response! I'll let you know if anything else comes up.
