### ISSUE TITLE
Compared by similarity metrics.

### ISSUE THREAD

**Issue by shiqingzhangCSU** [williamgilpin/fnn#4]
I think your job is very meaningful and exciting！
I want to reproduce the experiments in the compared.ipynb，and I wish the author can provide code to compare distances with different measures（see pic below）.
![image](https://user-images.githubusercontent.com/44834482/112757474-70bf4780-901c-11eb-8221-a9f179e10199.png)

I am looking for your reply！Thanks！

**Comment by williamgilpin** [comment]
Hey @shiqingzhangCSU thanks very much---I am working on a more full-featured release that will include a bunch of different similarity metrics (and several other useful things for working with embeddings). I'm a bit behind on getting it polished, but I'm hoping to return to it soon.

**Comment by williamgilpin** [comment]
Closing this for now, until the update is ready to go
