### ISSUE TITLE
TypeError: Input 'k' of 'TopKV2' Op has type float32 that does not match expected type of int32.

### ISSUE THREAD

**Issue by chahatraj** [williamgilpin/fnn#6]
In FNN loss regularizer, k appears to be of float type whereas int is expected.

**Comment by williamgilpin** [comment]
Thank you very much for identifying this issue! I will confirm it and add a cast in the next update. Just out out curiosity, what version of TensorFlow are you using? This sounds like a new issue.

**Comment by chahatraj** [comment]
I'm using version 2.4.1 and using the FNN loss function on google colab. Please let me know if I need to change the TensorFlow version.

**Comment by williamgilpin** [comment]
Hello, I am not getting this error on TF 2.5 on macOS. However, I was able to guess which line was causing the problem. See if the latest GitHub version solves your issue
